### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:443

### ISSUE THREAD

**Issue by Vexyr** [bakapear/ytt#1]
For some reason I get this error and I don't know why. Error;
```Error: connect ECONNREFUSED 127.0.0.1:443```
How to solve?

**Comment by bakapear** [comment]
Can you provide some code you used?

**Comment by Vexyr** [comment]
> Can you provide some code you used?

```require('ytt').query('pewdiepie', { filter: 'channel' })```

**Comment by bakapear** [comment]
It works for me though... Does it happen all the time or just sometimes?

**Comment by bakapear** [comment]
I've rewritten the entire package. If your problem still persists please open another issue.
