### ISSUE TITLE
Error on ?some? videos with method ytt.video(video_id)

### ISSUE THREAD

**Issue by Erfesto** [bakapear/ytt#10]
For example, videos [video1](https://www.youtube.com/watch?v=G3qQtf7jahE), [video2](https://www.youtube.com/watch?v=eyjyN_8DneM) gives error

Checking video with `await ytt.valid(video_id)` gives true
Searching videos with `await ytt.query('search text', { filter: 'video', num: 20 })` and finding that video is ok

But when trying to use `await ytt.video(video_id)`, it gives error
`TypeError: Cannot read property 'accessibilityData' of undefined
    at Object.makeVideoObject (/project/node_modules/ytt/src/lib/builder.js:107:125)
    at Object.module.exports [as video] (/project/node_modules/ytt/src/video.js:9:23)`

**Comment by bakapear** [comment]
Thanks for reporting the issue!

The endpoint for dislikes is no longer available so I removed it entirely from the video object in f7fa7e8407ece723217e405b2ee9c2865cc55cbe, that should fix it.
