### ISSUE TITLE
Empty query answer

### ISSUE THREAD

**Issue by laBecasse** [bakapear/ytt#4]
Hello,
First of all, thank you for this amazing package.
I discover some problems using the query method. The following queries lead to empty result, which is not the case in YT: 
1. joy departed
2. Marvin Gaye, 'What's Going On'  

The case 1. is maybe related to the fact that an album is attached to the answer. The case 2. may be caused by the quotes.

**Comment by bakapear** [comment]
```js
ytt.query('joy departed').then(r => console.log(r.items.length)) // 19 results
ytt.query('Marvin Gaye, \'What\'s Going On\'').then(r => console.log(r.items.length)) // 19 results
```

Both queries return results for me. Did you apply some filters or something?

**Comment by ghost** [comment]
Ok, you are right. Things are working now, but I did not change my code since this morning and I was sure that the answer set was empty. Does it possible that youtube have an evolving behaviour ?

**Comment by bakapear** [comment]
This ytt module is basically a site scraper. If the site changes its structure then this module breaks easily. So it's possible something changed for a short period of time that broke this module.
