### ISSUE TITLE
util.parse error 

### ISSUE THREAD

**Issue by laBecasse** [bakapear/ytt#5]
Hello, I realize that the [util.parse](https://github.com/bakapear/ytt/blob/c84f0365f365f5b0ac545c8d51cf1778285c7820/src/lib/util.js#L24) function leads to errors, because some scrapped pages does not contain `window["ytInitialData"] = `, but `var ytInitialData = ` instead. 

So consider the following `parse` function solves my error: 
```js
parse: x => main.between(x, 'var ytInitialData = ', '};', 1)
```

Is it possible to support the both alternatives ?

**Comment by ghost** [comment]
I also found similar remarks in : https://github.com/ytdl-org/youtube-dl/pull/25734#issuecomment-686455736

**Comment by bakapear** [comment]
Thank you for pointing this out. I also noticed it this morning and will push a fix in a second!
